# Generated by Django 2.2 on 2021-02-03 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20210119_0836'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='banner',
            field=models.ImageField(default='test.png', upload_to=''),
        ),
        migrations.AlterField(
            model_name='blog',
            name='dop',
            field=models.DateField(verbose_name='Date of Publication'),
        ),
    ]
